from django.conf import settings 


# DEFAULT_LIQPAY_PUBLIC_KEY = "sandbox_i29048427621"
# DEFAULT_LIQPAY_PRIVATE_KEY = "sandbox_RBR5FM04gXXt25MLzVmP7eyarKDWIKXw86MEMkvm"


DEFAULT_LIQPAY_PUBLIC_KEY = "i3466565002"
DEFAULT_LIQPAY_PRIVATE_KEY="85pd0UjyxXThv8RQpmPld4Z406wGZF4huAfqDHaB"


LIQPAY_PUBLIC_KEY  = getattr(settings, 'LIQPAY_PUBLIC_KEY', DEFAULT_LIQPAY_PUBLIC_KEY)
LIQPAY_PRIVATE_KEY = getattr(settings, 'LIQPAY_PRIVATE_KEY', DEFAULT_LIQPAY_PRIVATE_KEY)

