from django.conf import settings 

DEFAULT_MULTIPLE_CATEGORY = False
MULTIPLE_CATEGORY  = getattr(settings, 'MULTIPLE_CATEGORY', DEFAULT_MULTIPLE_CATEGORY) 

DEFAULT_ITEM_SEARCH_FIELDS = ['code',]
ITEM_SEARCH_FIELDS = getattr(settings, 'ITEM_SEARCH_FIELDS', DEFAULT_ITEM_SEARCH_FIELDS) 

DEFAULT_ITEM_URL_NAME = "item"
ITEM_URL_NAME = getattr(settings, 'ITEM_URL_NAME', DEFAULT_ITEM_URL_NAME)

