# Generated by Django 3.0.3 on 2020-02-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privat24Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='amount')),
                ('ccy', models.CharField(max_length=32, verbose_name='ccy')),
                ('details', models.CharField(max_length=128, verbose_name='details')),
                ('pay_way', models.CharField(max_length=32, verbose_name='pay way')),
                ('order', models.CharField(max_length=64, unique=True, verbose_name='order')),
                ('merchant', models.CharField(max_length=64, verbose_name='merchant')),
                ('state', models.CharField(max_length=32, verbose_name='state')),
                ('date', models.CharField(max_length=64, verbose_name='date')),
                ('signature', models.TextField(verbose_name='signature')),
                ('ext_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='ext details')),
                ('reference', models.CharField(blank=True, max_length=64, null=True, verbose_name='reference')),
                ('sender_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='sender phone')),
                ('raw_data', models.TextField(blank=True, null=True, verbose_name='raw data')),
            ],
            options={
                'swappable': 'PRIVAT24_TRANSACTION_MODEL',
            },
        ),
    ]
