# Generated by Django 3.0.3 on 2020-02-13 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(blank=True, null=True, verbose_name='Мета Заголовок')),
                ('meta_descr', models.TextField(blank=True, null=True, verbose_name='Мета Опис')),
                ('meta_key', models.TextField(blank=True, null=True, verbose_name='Мета ключові слова')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Посилання на публікацію')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Заголовок публікації')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент')),
                ('image', models.ImageField(blank=True, default='blog/test_blog.png', null=True, upload_to='', verbose_name='Картинка')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Оновлено')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Публікація',
                'verbose_name_plural': 'Публікації',
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(blank=True, null=True, verbose_name='Мета Заголовок')),
                ('meta_descr', models.TextField(blank=True, null=True, verbose_name='Мета Опис')),
                ('meta_key', models.TextField(blank=True, null=True, verbose_name='Мета Ключові слова')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис категорії')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Посилання')),
                ('image', models.ImageField(blank=True, default='blog/test_blog.png', null=True, upload_to='', verbose_name='Картинка категорії')),
                ('alt', models.CharField(blank=True, max_length=120, null=True, verbose_name='Альт до картинки')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Оновлено')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Коммент')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Оновлено')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk', models.CharField(blank=True, max_length=120, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.Post')),
            ],
            options={
                'verbose_name': 'Перегляд',
                'verbose_name_plural': 'Перегляди',
            },
        ),
    ]
