# Generated by Django 3.0.3 on 2020-02-22 15:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200222_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки'),
        ),
        migrations.AddField(
            model_name='post',
            name='alt_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альт до картинки'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uk',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_descr_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Опис'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_descr_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Опис'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_key_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мета ключові слова'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_key_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Мета ключові слова'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Посилання на публікацію'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_uk',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Посилання на публікацію'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Заголовок публікації'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Заголовок публікації'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='alt_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Альт до картинки'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='alt_uk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Альт до картинки'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_descr_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Опис'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_descr_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Опис'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_key_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Ключові слова'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_key_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Ключові слова'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Заголовок'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_title_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Мета Заголовок'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Посилання'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug_uk',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Посилання'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='title_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок'),
        ),
    ]
